Add section with title License and with content MIT is a link to LICE…
dipiash/nx-vite-react-ts-mantine-boilerplate pull request #60
Opened 2023-10-28 17:27 UTC by imrtls00

…NSE file in README.md.

## Description

Please include a summary of the changes and the issue number (if applicable). Please also include relevant motivation and context.

Fixes # (59)

## Type of Change

- [✅] Documentation update

## Checklist

- [✅] I have read the [contribution guidelines](CONTRIBUTING.md)
- [✅] My code follows the code style of this project
- [✅] I have performed a self-review of my own code
- [✅] I have made corresponding changes to the documentation
- [✅] My changes generate no new warnings
- [✅] New and existing unit tests pass locally with my changes

## Screenshots (if applicable)

![image](https://github.com/dipiash/nx-vite-react-ts-mantine-boilerplate/assets/68025467/2aa93104-5818-41b0-ae8f-59fa47b61752)

2023-10-28 17:33 UTC, imrtls00 commented
Solves the [Issue#59](#59)

2023-10-28 18:31 UTC, dipiash requested changes

2023-10-28 18:31 UTC, dipiash commented on README.md
> +## License
Could you move the license section on the bottom of readme file please?

2023-10-29 11:13 UTC, imrtls00 reviewed
Moved License section to bottom of README.md

2023-10-29 11:20 UTC, dipiash approved these changes

2023-10-29 13:06 UTC, merged